server:
  port: 10002

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: hutu-order-admin
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/hutu-order?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-test-query: select 1
    # sa-token配置
  redis:
    host: localhost
    database: 0
    password: pass
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 30
        min-idle: 2
        time-out: 3000

security:
  jwt:
    secret: hutu-admin-2023
    expire: 86400
    header: Token
    redis-key-prefix: token_key-token
    token-prefix: Bearer

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

logging:
  config: classpath:logback-dev.xml
  level:
    org.nott.admin.mapper: debug

swagger2:
  group-name: "糊涂点餐-后台管理端"