server:
  port: 10001

business:
  prefix-eat-in: 'H'
  prefix-take-out: 'T'
  order-expire: 300
  order-length: 3
  seq-length: 16
  check-type: delayedQueue

order:
  queue-length:
    prepare: 12


spring:
  redis:
    host: localhost
    password:
    database: 3
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 30
        min-idle: 2
        time-out: 3000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: hutu-order
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/hutu-order?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-test-query: select 1

  security:
    load: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-dev.xml
#  level:
#    org.nott.web.mapper: debug

alipay:
  appId:
  privateKey:
  publicKey:
  signType: RSA2
  notifyUrl:
  app:
    appId:
    appSecret:

weixinpay:
  mchId:
  appId:
  apiV3Key:
  notifyUrl:
  privateKeyPath:
  merchantSerialNumber:

wechat:
  app:
    appId:
    appSecret:

payment:
  package:
    name: org.nott.payment

swagger2:
  group-name: "糊涂点餐-用户端"