server:
  port: 9901

web:
  base-path: '/usr1/local'
  upload-path: '/hutu-order/web/upload/static/'

logging:
  config: classpath:logback-dev.xml
  level:
    org.nott.web.mapper: debug

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: hutu-order-oss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/hutu-order?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-test-query: select 1
  servlet:
    multipart:
      max-file-size: 20MB
security:
  jwt:
    secret: hutu-admin-2023
    expire: 86400
    header: Token
    redis-key-prefix: hutu-login_token_key-token
    token-prefix: Bearer